version: '2'
services:
  influxdb:
    image: influxdb:1.4.2-alpine
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: influxdb-volume
    volumes_from:
      - influxdb-volume
  influxdb-volume:
    network_mode: "none"
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    environment:
      - SERVICE_UID=0
      - SERVICE_GID=0
      - SERVICE_VOLUME=/var/lib/influxdb
    volumes:
      - /var/lib/influxdb
    volume_driver: ${VOLUME_DRIVER}
    image: rawmind/alpine-volume:0.0.2-2

