version: '2'
services:
  influxdb:
    image: influxdb:1.4.2-alpine
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: influxdb-volume
    volumes_from:
      - influxdb-volume
  influxdb-volume:
    network_mode: "none"
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    environment:
      - SERVICE_UID=0
      - SERVICE_GID=0
      - SERVICE_VOLUME=/var/lib/influxdb
    volumes:
      - influxdb_data:/var/lib/influxdb
    volume_driver: ${VOLUME_DRIVER}
    image: rawmind/alpine-volume:0.0.2-2

  grafana:
    environment:
      GF_SECURITY_ADMIN_USER: ${admin_username}
      GF_SECURITY_ADMIN_PASSWORD: ${admin_password}
      GF_SECURITY_SECRET_KEY: ${secret_key}
      GF_INSTALL_PLUGINS: ${install_plugins}
    image: grafana/grafana:4.6.3
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: grafana-data
    external_links:
    - influxdb:influxdb
    volumes_from:
      - grafana-data
  grafana-data:
    network_mode: "none"
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    environment:
      - SERVICE_UID=104
      - SERVICE_GID=107
      - SERVICE_VOLUME=/usr/lib/grafana
    volumes:
      - grafana-data:/usr/lib/influxdb
    volume_driver: ${VOLUME_DRIVER}
    image: rawmind/alpine-volume:0.0.2-2
