.catalog:
  name: "RethinkDB"
  version: "2.3.5"
  description: "(Experimental) NoSQL-Database"
  uuid: rethinkdb-0
  questions:
    - variable: "rethinkdb_volume_driver"
      description: ""
      label: "Volume Driver:"
      required: true
      type: "string"
      default: "local"
    - variable: "rethinkdb_proxy_port"
      description: ""
      label: "Proxy Port:"
      required: true
      type: "int"
      default: 8080

version: '2'
services:
  rethinkdb:
    scale: 1
    start_on_create: true
  rethinkdb-proxy:
    scale: 1
    start_on_create: true
