version: '2'
catalog:
  name: "MongoDB"
  version: "3.4-rancher2"
  description: "MongoDB Replica Set"
  uuid: mongodb-1
  minimum_rancher_version: v1.6.10
  questions:
    - variable: replset_name
      description: "Name of the MongoDB replicaSet"
      label: "ReplicaSet Name"
      type: "string"
      required: true
      default: "rs0"
    - variable: debug
      description: "Enable Debug log for Mongo containers"
      label: "Debug"
      type: "string"
      required: false
      default: ""
    - variable: "VOLUME_DRIVER"
      description: "The VOLUME driver to associate with this server"
      label: "VOLUME Driver"
      required: true
      default: "local"
      type: enum
      options:
        - local
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
    - variable: mongo_scale
      description: "How many containers the MongoDB will scale to?"
      label: "mongo scale"
      type: "int"
      required: true
      default: "3"
    - variable: "MONGO_INITDB_ROOT_USERNAME"
      description: "Admin user name:"
      label: "Admin user"
      required: true
      default: root
      type: "string"
    - variable: "MONGO_INITDB_ROOT_PASSWORD"
      description: "Initial password for root user:"
      label: "Admin password"
      required: true
      default: rootpasswoord
      type: "string"
    - variable: "MONGO_EXTERNAL_PORT"
      description: "Listen port for mongodb:"
      label: "Mongo port"
      required: true
      default: 27017
      type: "int"
services:
  mongo-cluster:
    scale: ${mongo_scale}
    retain_ip: true
    metadata:
      mongo:
        yml:
          replset.name: "${replset_name}"
