.catalog:
  name: "Redis"
  version: "4.0.7"
  description: "A cluster of Redis instances for High Availability on Rancher"
  minimum_rancher_version: v1.6.0
version: '2'
services:
  redis-sentinel:
    retain_ip: true
    scale: 3
    start_on_create: true
  redis-server:
    retain_ip: true
    scale: 3
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 6379
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: none
      reinitializing_timeout: 60000
  redis-commander:
    scale: 1