name: Apache Zookeeper
description: |
  (Experimental) Zookeeper cluster JEFFK
version: 3.4.8-rancher1
category: Clustering
maintainer: "Raul Sanchez <rawmind@gmail.com>"
projectURL: https://github.com/rawmind0/alpine-zk
license: 