version: '2'
services:
  graylog-server:
    restart: always
    environment:
      GRAYLOG_MONGODB_URI: "mongodb://${DB_USER}:${DB_PW}@${DB_URIS}/${DB_NAME}?replicaSet=${RS_NAME}"
      GRAYLOG_PASSWORD_SECRET: ${GRAYLOG_PASSWORD_SECRET}
      GRAYLOG_ROOT_PASSWORD_SHA2: ${GRAYLOG_ROOT_PASSWORD_SHA2}
      GRAYLOG_WEB_ENDPOINT_URI: ${GRAYLOG_WEB_ENDPOINT_URI}
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    image: intlfcstone/graylog-rancher:v2.4.3-1
    external_links:
      - ${ES_LINK}:elasticsearch
      - ${ZK_LINK}:zk
      - ${KAFKA_LINK}:broker
    labels:
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: graylog-journal
    volumes_from:
      - graylog-journal
  graylog-journal:
    environment:
      SERVICE_VOLUME: /data/db
      SERVICE_UID: 1100
      SERVICE_GID: 1100
    labels:
        io.rancher.container.start_once: true
        network_mode: none
        io.rancher.container.hostname_override: container_name
    volumes:
      - journal:/data/db
    image: rawmind/alpine-volume:0.0.2-1
volumes:
  journal:
    driver: ${VOLUME_DRIVER}
    per_container: true