version: '2'
catalog:
  name: "GrayLog"
  version: "v2.4.3-1"
  description: "Graylog cluster"
  uuid: graylogserver-2
  minimum_rancher_version: v1.6.10
  questions:
    - variable: "DB_USER"
      description: "MongoDB Username for GrayLog to use"
      label: "MongoDB username"
      required: true
      default: "graylog"
      type: "string"
    - variable: "DB_PW"
      description: "MongoDB password"
      label: "MongoDB password"
      required: true
      default: "password"
      type: "string"
    - variable: GRAYLOG_PASSWORD_SECRET
      description: |
        Secret to secure/pepper the stored user passwords - use at least 64 characters.
        You may generate it with pwgen -N 1 -s 96 or something similar
      label: "Password secret"
      type: "string"
      required: true
      default: "somepasswordpepper"
    - variable: GRAYLOG_ROOT_PASSWORD_SHA2
      description: |
        SHA2 encrypted password for admin user.
        You may generate it with echo -n YOURPASSWORD | shasum -a 256
      label: "Admin password"
      type: "string"
      required: true
      default: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
    - variable: GRAYLOG_WEB_ENDPOINT_URI
      description: |
        URI of the Graylog API.
        You should point this at your load balancer
      label: "APU URI"
      type: "string"
      required: true
      default: "http://127.0.0.1:9000/api"
    - variable: "VOLUME_DRIVER"
      description: "The VOLUME driver to associate with this server"
      label: "VOLUME Driver"
      required: true
      default: "local"
      type: enum
      options:
        - local
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
    - variable: cluster_size
      description: "Number of servers:"
      label: "Cluster size"
      type: "int"
      required: true
      default: "3"
services:
  mongo-cluster:
    scale: ${cluster_size}

