version: '2'
catalog:
  name: "GrayLog"
  version: "3.4-rancher2"
  description: "Graylog cluster"
  uuid: graylogserver-2
  minimum_rancher_version: v1.6.10
  questions:
    - variable: GRAYLOG_PASSWORD_SECRET
      description: |
        Secret to secure/pepper the stored user passwords - use at least 64 characters
        You may generate it with pwgen -N 1 -s 96 or something similar
      label: "Password secret"
      type: "string"
      required: true
      default: "somepasswordpepper"
    - variable: debug
      description: "Enable Debug log for Mongo containers"
      label: "Debug"
      type: "string"
      required: false
      default: ""
    - variable: "VOLUME_DRIVER"
      description: "The VOLUME driver to associate with this server"
      label: "VOLUME Driver"
      required: true
      default: "local"
      type: enum
      options:
        - local
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
    - variable: mongo_scale
      description: "How many containers the MongoDB will scale to?"
      label: "mongo scale"
      type: "int"
      required: true
      default: "3"
    - variable: "MONGO_INITDB_ROOT_USERNAME"
      description: "Admin user name:"
      label: "Admin user"
      required: true
      default: root
      type: "string"
    - variable: "MONGO_INITDB_ROOT_PASSWORD"
      description: "Initial password for root user:"
      label: "Admin password"
      required: true
      default: rootpasswoord
      type: "string"
    - variable: "MONGO_EXTERNAL_PORT"
      description: "Listen port for mongodb:"
      label: "Mongo port"
      required: true
      default: 27017
      type: "int"
services:
  mongo-cluster:
    scale: ${mongo_scale}
    retain_ip: true
    metadata:
      mongo:
        yml:
          replset.name: "${replset_name}"
