version: '2'
catalog:
  name: "GrayLog"
  version: "v2.4.3-1"
  description: "Graylog cluster"
  uuid: graylogserver-2
  minimum_rancher_version: v1.6.10
  questions:
    - variable: "DB_USER"
      description: "Mongo Username for GrayLog to use"
      label: "Mongo username"
      required: true
      default: "graylog"
      type: "string"
    - variable: "DB_PW"
      description: "Mongo password"
      label: "Mongo password"
      required: true
      default: "password"
      type: "string"
    - variable: DB_NAME
      description: "Mongo database"
      label: "Mongo database to use"
      type: "string"
      required: true
      default: "graylog"
    - variable: RS_NAME
      description: "Name of the replica set in mongo"
      label: "Replica set name"
      type: "string"
      required: true
      default: "rs01"
    - variable: DB_URIS
      description: "Comma-seperated list of mongodb locations:ports"
      label: "DB Locations"
      type: "string"
      required: true
      default: "mongodb-node01:27017,mongodb-node02:27017,mongodb-node03:27017"
    - variable: GRAYLOG_PASSWORD_SECRET
      description: |
        Secret to secure/pepper the stored user passwords - use at least 64 characters.
        You may generate it with pwgen -N 1 -s 96 or something similar
      label: "Password secret"
      type: "string"
      required: true
      default: "somepasswordpepper"
    - variable: GRAYLOG_ROOT_PASSWORD_SHA2
      description: |
        SHA2 encrypted password for admin user.
        You may generate it with echo -n YOURPASSWORD | shasum -a 256
      label: "Admin password"
      type: "string"
      required: true
      default: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
    - variable: GRAYLOG_WEB_ENDPOINT_URI
      description: |
        URI of the Graylog API.
        You should point this at your load balancer
      label: "API URI"
      type: "string"
      required: true
      default: "http://127.0.0.1:9000/api"
    - variable: "VOLUME_DRIVER"
      description: "The VOLUME driver to associate with this server"
      label: "VOLUME Driver"
      required: true
      default: "local"
      type: enum
      options:
        - local
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
    - variable: "ES_LINK"
      description: "ElasticSearch ingestion node"
      label: "ElasticSearch Service"
      default: "es-cluster/es-client"
      required: true
      type: "service"
    - variable: "ZK_LINK"
      description: "Zookeeper service - Provides intra-network connectivity to Zookeeper"
      label: "Zookeeper service(s)"
      default: "zookeeper/zk"
      required: false
      type: "service"
    - variable: "KAFKA_LINK"
      description: "Kafka service - Provides intra-network connectivity to kafka"
      label: "Kafka broker service(s)"
      default: "kafka/broker"
      required: false
      type: "service"
    - variable: cluster_size
      description: "Number of servers:"
      label: "Cluster size"
      type: "int"
      required: true
      default: "3"
services:
  graylog-server:
    scale: ${cluster_size}

