.catalog:
  name: "MongoDB"
  version: "3.0.0-rancher1"
  description: "MongoDB Replica Set"
  uuid: mongodb-0
  minimum_rancher_version: v0.46.0
  questions:
    - variable: replset_name
      description: "Name of the MongoDB replicaSet"
      label: "ReplicaSet Name"
      type: "string"
      required: true
      default: "rs0"
    - variable: debug
      description: "Enable Debug log for Mongo containers"
      label: "Debug"
      type: "string"
      required: false
      default: ""
mongo-cluster:
  scale: 3
  retain_ip: true
  metadata:
    mongo:
      yml:
        replset.name: "${replset_name}"
